# Generated by Django 5.0.10 on 2025-01-11 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("release_date", models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
