# Generated by Django 5.0.10 on 2025-01-22 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="body",
        ),
    ]
