# Generated by Django 5.0.10 on 2025-01-22 20:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_article_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="body",
            field=ckeditor_uploader.fields.RichTextUploadingField(default=""),
        ),
    ]
